
spring:
  application:
    name: study-spring-ai
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration
  ai:
    # 阿里灵积
    dash-scope:
      api-key: sk-63aaa233142246f9a4642f5bf2552baa
      chat:
        options:
          model: qwen-max
      embedding:
        options:
          model: text-embedding-v2
    # openai
    openai:
      chat:
        # 这里关闭就可以指定ChatModel构建ChatClient
        enabled: false
      api-key:
    mcp:
      client:
        type: async
        name: webflux-mcp-client
        version: 1.0.0
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              url: http://localhost:8088

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG